runtime: custom
env: flex
service: cv
threadsafe: true

env_variables:
  API_URL: "https://webapi-dev.antoinefusilier.dev"
  BUCKET: "cv.antoinefusilier.dev"

# automatic_scaling:
#   max_num_instances: 30
manual_scaling:
  instances: 1
